<a href="https://colab.research.google.com/github/amitya369/Data_science_with_python_lab/blob/main/dsp_lab_unito3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class BankAccount:
    def __init__(self, balance=0):
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        return self.balance

    def withdraw(self, amount):
        if amount > self.balance:
            return "Insufficient funds"
        else:
            self.balance -= amount
            return self.balance

    def check_balance(self):
        return self.balance

# AMIT KUMAR YADAV


In [2]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def get_info(self):
        return f"Name: {self.name}, Age: {self.age}"

class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)
        self.student_id = student_id

    def get_student_info(self):
        return f"Name: {self.name}, Age: {self.age}, Student ID: {self.student_id}"

# AMIT KUMAR YADAV


In [3]:
import numpy as np

random_array = np.random.uniform(0, 1, size=(5,))
print(random_array)

# AMIT KUMAR YADAV


[0.32346774 0.22871456 0.55005389 0.99416938 0.03507775]


In [4]:
import numpy as np

random_array = np.random.rand(12)
reshaped_array = random_array.reshape(3, 4)
maximum_value = reshaped_array.max()
minimum_value = reshaped_array.min()

print(reshaped_array)
print("Max:", maximum_value)
print("Min:", minimum_value)

# AMIT KUMAR YADAV


[[0.04344996 0.32369599 0.75182524 0.74711325]
 [0.97984004 0.4850517  0.4726656  0.1276764 ]
 [0.00398526 0.11928327 0.47230594 0.67059695]]
Max: 0.9798400376159647
Min: 0.003985261878888924


In [5]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

# AMIT KUMAR YADAV


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [6]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

print(array[2])
print(array[1:4])

# AMIT KUMAR YADAV


30
[20 30 40]


In [7]:
import numpy as np

array = np.array([1, 2, 3])
broadcasted_array = array + 5
print(broadcasted_array)

# AMIT KUMAR YADAV


[6 7 8]


In [8]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])
print(matrix[:, 1])

# AMIT KUMAR YADAV


6
[2 5 8]
